/**
 * GET /api/intelligence?countryId=india|singapore
 *
 * Returns a structured IntelligenceReport generated by the AI engine.
 * The report is cached server-side for 30 minutes, keyed by country.
 *
 * Response shape: IntelligenceApiResponse
 *   Success: { report: IntelligenceReport; generatedAt: string }
 *   Error:   { error: string }
 */

import { generateIntelligenceReport } from "@/features/geopolitical-intelligence/services/intelligenceService";
import type { IntelligenceApiResponse } from "@/features/geopolitical-intelligence";
import { writeCorridorStatus } from "@/lib/signal-bus";
import { COUNTRY_REGISTRY } from "@/data/countries";


import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// Generous timeout — Groq generation can take 15-30 seconds with large prompts
export const maxDuration = 60;

export async function GET(request: NextRequest) {
  try {
    const countryId = request.nextUrl.searchParams.get("countryId") ?? "india";
    const country = COUNTRY_REGISTRY[countryId] ?? COUNTRY_REGISTRY["india"]!;

    const report = await generateIntelligenceReport(country);

    // Publish corridor status to cross-module signal bus
    const threat = report.current_operational_assessment?.threat_level;
    if (threat) {
      const statusMap: Record<string, "CRITICAL" | "ELEVATED" | "NORMAL" | "NO_SIGNAL"> = {
        Critical: "CRITICAL",
        High: "ELEVATED",
        Medium: "NORMAL",
        Low: "NORMAL",
      };
      writeCorridorStatus({
        corridorName: "Strait of Hormuz",
        status: statusMap[threat] ?? "NO_SIGNAL",
      });
    }

    const body: IntelligenceApiResponse = {
      report,
      generatedAt: new Date().toISOString(),
    };

    return NextResponse.json(body, {
      headers: {
        "Cache-Control": "no-store",
      },
    });
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Intelligence generation failed";

    console.error("[/api/intelligence] Error:", message);

    const body: IntelligenceApiResponse = {
      error: message,
    };

    return NextResponse.json(body, { status: 500 });
  }
}
