/**
 * GET /api/intelligence
 *
 * Returns a structured IntelligenceReport generated by the AI engine.
 * The report is cached server-side for 30 minutes.
 *
 * Response shape: IntelligenceApiResponse
 *   Success: { report: IntelligenceReport; generatedAt: string }
 *   Error:   { error: string }
 */

import { generateIntelligenceReport } from "@/features/geopolitical-intelligence/services/intelligenceService";
import type { IntelligenceApiResponse } from "@/features/geopolitical-intelligence";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// Generous timeout — Groq generation can take 15-30 seconds with large prompts
export const maxDuration = 60;

export async function GET(): Promise<Response> {
  try {
    const report = await generateIntelligenceReport();

    const body: IntelligenceApiResponse = {
      report,
      generatedAt: new Date().toISOString(),
    };

    return Response.json(body, {
      headers: {
        "Cache-Control": "no-store",
      },
    });
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Intelligence generation failed";

    console.error("[/api/intelligence] Error:", message);

    const body: IntelligenceApiResponse = {
      error: message,
    };

    return Response.json(body, { status: 500 });
  }
}
